- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create an EC2 instance
      ec2:
        key_name: MyEC2KeyPair
        instance_type: t2.small
        region: ap-southeast-1
        group_id: sg-77602e11
        image: ami-1fbad07c
        wait: true
        vpc_subnet_id: subnet-9d05befa
        volumes:
           - device_name: /dev/sda1
             volume_type: gp2
             volume_size: 20
             delete_on_termination: true
        assign_public_ip: yes
      register: ec2_output


    - name: Add the newly created instance to the inventory
      lineinfile:
        path: /etc/ansible/hosts
        line: '{{ item.private_dns_name }}  ansible_host={{ item.private_ip }} ansible_user=centos host_region={{ item.region }} instance_type={{ item.instance_type }} host_az={{ item.placement }} host_os=CentOS os_version=7 '
      with_items: "{{ ec2_output.instances }}"
