    - name: Install MySQL dependencies
      yum:
        name: mysql-devel
      become: true
    
    - name: Install MySQL Driver Dependencies
      pip:
        name: '{{ item }}'
        state: present
      with_items:
        - MySQL-python
      become: true
